# -*- coding: utf-8 -*-
"""introducción

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zVcDZw1pXuBu0cyL9XuNCb80ktWb4hl8
"""

8**4 # potencia

5%3 # resuido

5//2

print("Hello, world")

nombre="isaac"
print(nombre)

"""##que tipo de objetivo esta escrito"""

x=5
y=2

type(x/y)

type(nombre)

type(x)

x=5
print(x)

"""$$ax^2+bx+c=0$$

LaTeX
$$e^{i\pi}+1=0.$$

# introduccion a objetos ⏰.

Los primero objetos que veremos:


1.    Numeros (int, float), strings ("Hola")
2.    Listas.
3.    Variables





referencia[Python OOP](https://olympics.com/es/paris-2024)

Hay funciones que estan creadas dentro de python
"""

