# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wpmoxT62olHwinjXpOMSj9XpGHPZamuS

Las listas son objetos que se escriben conn []
"""

L =[]

type(L) # nos dice que tipo de objeto

# la funcion range() (es un generador de etiquetas)
range(10)

for i in range(10):
  print(i)

for i in range(10):
  L.append(i) # Agrega elementos
  print(L)

L[0:4]

"""¿Como elegir a los pares?"""

P = []
for i in range(10):
    if i % 2 == 0:
      P.append(i)
print(P)    #  seleccionar los numeros pares

I = [ i for i in L if i%2==1] #poner los numeros nones

I

P + I # Junta  las listas

sP =set(P)
sI = set(I)

print(sP)
print(sI)